#!/bin/bash
export TER=$PWD
export Ter=$TER
export ter=$TER
alias Ter='$TER/TER.sh'
alias ter="Ter"
alias TER="Ter"
export TER_data='/dati/Data_CGEM_IHEP_Integration_2019'
export exe_ter='/home/ihep_data/TIGER_Event_Reconstruction/TER.sh'
